version: '3'
services:
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${EXPOSE_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_FOLDER}:/var/lib/mysql